# Generated by Django 5.2.7 on 2025-10-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Subido'), ('signed', 'Firmado'), ('flattened', 'Aplanado/Rasterizado')], default='uploaded', max_length=20),
        ),
    ]
