# Generated by Django 5.2.7 on 2026-03-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Subido'), ('signed', 'Firmado'), ('flattened', 'Aplanado/Rasterizado'), ('flattened_original', 'Original Aplanado')], default='uploaded', max_length=20),
        ),
    ]
