# Generated by Django 5.2.7 on 2026-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
